name: vipul_task_master
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Navigation
  go_router: ^10.1.2
  # Dependency Injection
  get_it: ^7.6.4
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  # Utils
  uuid: ^3.0.7
  intl: ^0.18.1
  # Device specific
  device_info_plus: ^9.0.3
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



