name: vipul_task_master
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Navigation
  go_router: ^10.1.2
  # Dependency Injection
  get_it: ^7.6.4
  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  # Utils
  uuid: ^3.0.7
  intl: ^0.18.1
  # Device specific
  device_info_plus: ^9.0.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.14.3"


  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/icons/




